-- Database migration for Large Motors (PostgreSQL)
-- Creates tables and inserts initial seed data
--
-- Fixes applied vs. the original file:
--   1. `categories` was missing a comma before `description`.
--   2. `service requests` is not a valid identifier (space) — quoted
--      identifiers are painful to work with everywhere, so it's renamed
--      to `service_requests`.
--   3. `integer primary key` doesn't auto-increment in PostgreSQL the way
--      it does in SQLite — switched to `GENERATED ALWAYS AS IDENTITY` so
--      inserts can omit the id column.

BEGIN;

CREATE TABLE vehicles (
    id  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    make        text NOT NULL,
    model       text NOT NULL,
    year        integer NOT NULL,
    price       numeric(10, 2) NOT NULL,
    category_id integer REFERENCES categories(id),
    description text,
    image_url   text
);

CREATE TABLE users (
    id  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password text NOT NULL,
    role     text NOT NULL,
    email    text NOT NULL UNIQUE
);

CREATE TABLE categories (
    id  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    description text
);

CREATE TABLE reviews (
    id  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL REFERENCES vehicles(id),
    user_id    integer NOT NULL REFERENCES users(id),
    rating     integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment    text,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_posts (
    id    integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title      text NOT NULL,
    content    text NOT NULL,
    author_id  integer NOT NULL REFERENCES users(id),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_comments (
    id    integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    post_id    integer NOT NULL REFERENCES blog_posts(id),
    user_id    integer NOT NULL REFERENCES users(id),
    comment    text NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE service_requests (
    id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vehicle_id   integer NOT NULL REFERENCES vehicles(id),
    user_id      integer NOT NULL REFERENCES users(id),
    service_type text NOT NULL,
    description  text,
    status       text NOT NULL,
    created_at   timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contacts (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES users(id),
    message    text NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle_images (
    id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL REFERENCES vehicles(id),
    image_url  text NOT NULL
);

-- ---------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------

-- Users: staff accounts + the customers referenced in the site's review
-- section. Passwords below are placeholder bcrypt-style hashes, NOT real
-- hashes of any actual password — swap in real bcrypt/argon2 hashes
-- generated by your auth layer before using this anywhere but a demo.
INSERT INTO users (username, password, role, email) VALUES
    ('gary_sales',   '$2b$12$placeholderHashGary000000000000000000000000000', 'staff',    'gary@largemotors.example'),
    ('denise_ops',   '$2b$12$placeholderHashDenise00000000000000000000000', 'staff',    'denise@largemotors.example'),
    ('kevin_cr',     '$2b$12$placeholderHashKevin000000000000000000000000', 'staff',    'kevin@largemotors.example'),
    ('marcus_sales', '$2b$12$placeholderHashMarcusS0000000000000000000000', 'staff',    'marcus.s@largemotors.example'),
    ('admin',        '$2b$12$placeholderHashAdmin000000000000000000000000', 'admin',    'admin@largemotors.example'),
    ('dana_r',       '$2b$12$placeholderHashDanaR000000000000000000000000', 'customer', 'dana.r@example.com'),
    ('marcus_t',     '$2b$12$placeholderHashMarcusT0000000000000000000000', 'customer', 'marcus.t@example.com'),
    ('priya_k',      '$2b$12$placeholderHashPriyaK00000000000000000000000', 'customer', 'priya.k@example.com'),
    ('big_sal',      '$2b$12$placeholderHashBigSal00000000000000000000000', 'customer', 'sal@example.com'),
    ('jenny_o',      '$2b$12$placeholderHashJennyO00000000000000000000000', 'customer', 'jenny.o@example.com'),
    ('tom_w',        '$2b$12$placeholderHashTomW000000000000000000000000',  'customer', 'tom.w@example.com');

-- Vehicles: current lot inventory
INSERT INTO vehicles (make, model, year, price, description, image_url) VALUES
    ('Meridian', 'Coupe',  2011, 2995.00,
     'Runs when warm, cold, or medium. Aftermarket duct-tape trim, matches interior. Comes with the good spare, not the donut.',
     '/images/vehicles/meridian-coupe-2011.jpg'),
    ('Highline', 'Sedan',  2014, 4400.00,
     'Only driven to church, allegedly. Minor sunroof (permanently open). Brakes make a sound that means it''s working.',
     '/images/vehicles/highline-sedan-2014.jpg'),
    ('Vandale',  'Wagon',  2008, 1750.00,
     'Some rust is structural, some is decorative. Radio only plays AM, which builds character. Never been in an accident we know about.',
     '/images/vehicles/vandale-wagon-2008.jpg'),
    ('Cresthill','SUV',    2016, 6800.00,
     'Four doors, four tires, one steering wheel. Recently detailed to remove evidence. Backed by our famous handshake guarantee.',
     '/images/vehicles/cresthill-suv-2016.jpg');

COMMIT;